// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLPCPayRollApp.Data;

#nullable disable

namespace NLPCPayRollApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230529023700_cadrelevel")]
    partial class cadrelevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NLPCPayRollApp.Models.CadreLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CadreLevels");
                });

            modelBuilder.Entity("NLPCPayRollApp.Models.PayrollComponents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasicSalary")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<int>("CadreLevelId")
                        .HasColumnType("int");

                    b.Property<int>("Dressing")
                        .HasColumnType("int");

                    b.Property<int>("Entertainment")
                        .HasColumnType("int");

                    b.Property<int>("Furniture")
                        .HasColumnType("int");

                    b.Property<int>("GrossIncome")
                        .HasColumnType("int");

                    b.Property<int>("Housing")
                        .HasColumnType("int");

                    b.Property<int>("LifeAssurance")
                        .HasColumnType("int");

                    b.Property<int>("Lunch")
                        .HasColumnType("int");

                    b.Property<int>("NHF")
                        .HasColumnType("int");

                    b.Property<int>("NHIS")
                        .HasColumnType("int");

                    b.Property<int>("NPS")
                        .HasColumnType("int");

                    b.Property<int>("OtherAllowances")
                        .HasColumnType("int");

                    b.Property<int>("Passage")
                        .HasColumnType("int");

                    b.Property<int>("TaxPayable")
                        .HasColumnType("int");

                    b.Property<int>("ThirteenthMonth")
                        .HasColumnType("int");

                    b.Property<int>("Transport")
                        .HasColumnType("int");

                    b.Property<int>("Utility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CadreLevelId")
                        .IsUnique();

                    b.ToTable("PayrollComponents");
                });

            modelBuilder.Entity("NLPCPayRollApp.Models.PayrollComponents", b =>
                {
                    b.HasOne("NLPCPayRollApp.Models.CadreLevel", null)
                        .WithOne("PayrollComponents")
                        .HasForeignKey("NLPCPayRollApp.Models.PayrollComponents", "CadreLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NLPCPayRollApp.Models.CadreLevel", b =>
                {
                    b.Navigation("PayrollComponents")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
