// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLPCPayRollApp.Data;

#nullable disable

namespace NLPCPayRollApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NLPCPayRollApp.Models.CadreLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CadreLevels");
                });

            modelBuilder.Entity("NLPCPayRollApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CadreLevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("NLPCPayRollApp.Models.PayrollComponents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BasicSalary")
                        .HasColumnType("float");

                    b.Property<double>("Bonus")
                        .HasColumnType("float");

                    b.Property<int>("CadreLevelId")
                        .HasColumnType("int");

                    b.Property<double>("Dressing")
                        .HasColumnType("float");

                    b.Property<double>("Entertainment")
                        .HasColumnType("float");

                    b.Property<double>("Furniture")
                        .HasColumnType("float");

                    b.Property<double>("GrossIncome")
                        .HasColumnType("float");

                    b.Property<double>("Housing")
                        .HasColumnType("float");

                    b.Property<double>("LifeAssurance")
                        .HasColumnType("float");

                    b.Property<double>("Lunch")
                        .HasColumnType("float");

                    b.Property<double>("NHF")
                        .HasColumnType("float");

                    b.Property<double>("NHIS")
                        .HasColumnType("float");

                    b.Property<double>("NPS")
                        .HasColumnType("float");

                    b.Property<double>("OtherAllowances")
                        .HasColumnType("float");

                    b.Property<double>("Passage")
                        .HasColumnType("float");

                    b.Property<double>("TaxPayable")
                        .HasColumnType("float");

                    b.Property<double>("ThirteenthMonth")
                        .HasColumnType("float");

                    b.Property<double>("Transport")
                        .HasColumnType("float");

                    b.Property<double>("Utility")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CadreLevelId")
                        .IsUnique();

                    b.ToTable("PayrollComponents");
                });

            modelBuilder.Entity("NLPCPayRollApp.Models.PayrollComponents", b =>
                {
                    b.HasOne("NLPCPayRollApp.Models.CadreLevel", null)
                        .WithOne("PayrollComponents")
                        .HasForeignKey("NLPCPayRollApp.Models.PayrollComponents", "CadreLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NLPCPayRollApp.Models.CadreLevel", b =>
                {
                    b.Navigation("PayrollComponents")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
